name: auto-merge

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'

jobs:
  push-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: nocobase/nocobase
          ssh-key: ${{ secrets.NOCOBASE_DEPLOY_KEY }}
          persist-credentials: true
          fetch-depth: 0
      - name: main -> next(nocobase)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout main
          git pull origin main
          git checkout next
          git merge main
          git push origin next
      - name: push nocobase(next)
        uses: ad-m/github-push-action@master
        with:
          branch: next
          ssh: true
          repository: nocobase/nocobase
          tags: true
          atomic: true
